### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [AlexMNet/MMM-TheSpaceDevs#7]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by AlexMNet** [comment]
Hi @KristjanESPERANTO thank you for the heads up. Will add a license tonight!

**Comment by KristjanESPERANTO** [comment]
@AlexMNet Great! Thanks for this nice module! :smiley:

**Comment by AlexMNet** [comment]
@KristjanESPERANTO thank you! I have now added the MIT License. 🙂

**Comment by KristjanESPERANTO** [comment]
Nice! Now since the licence is clear the screenshot can be shown on the list :slightly_smiling_face:
